### ISSUE TITLE
For the fairness of the improved baseline

### ISSUE THREAD

**Issue by Changes92** [MCG-NJU/TIA#2]
Hi, thanks for your work. Could you please release your interpolated data? In this work, you have given an improved baseline using the style-transferred data, which should be released completely for the followed works.

I think that the comparison has been unfair in the benchmark tables since most counterparts don't utilize extra data (style-transfer is the core contribution for the only two counterparts using it), and we all know that it plays a critical role to achieve a high result. Considering the fairness of the following works, we strongly hope that you can release the interpolated data, keeping the fairness of the usage of data since different cyclegan training will make it more unreproducible.

**Comment by drickzsy** [comment]
> Hi, thanks for your work. Could you please release your interpolated data? In this work, you have given an improved baseline using the style-transferred data, which should be released completely for the followed works.
> 
> I think that the comparison has been unfair in the benchmark tables since most counterparts don't utilize extra data (style-transfer is the core contribution for the only two counterparts using it), and we all know that it plays a critical role to achieve a high result. Considering the fairness of the following works, we strongly hope that you can release the interpolated data, keeping the fairness of the usage of data since different cyclegan training will make it more unreproducible.

Hi, can you run this code directly? I think a part of the necessary code is missing.

**Comment by Changes92** [comment]
> > Hi, thanks for your work. Could you please release your interpolated data? In this work, you have given an improved baseline using the style-transferred data, which should be released completely for the followed works.
> > I think that the comparison has been unfair in the benchmark tables since most counterparts don't utilize extra data (style-transfer is the core contribution for the only two counterparts using it), and we all know that it plays a critical role to achieve a high result. Considering the fairness of the following works, we strongly hope that you can release the interpolated data, keeping the fairness of the usage of data since different cyclegan training will make it more unreproducible.
> 
> Hi, can you run this code directly? I think a part of the necessary code is missing.

No, I didn't run since it seems that the authors never reply to the issues.

**Comment by KosumosuL** [comment]
Sorry for the late reply to you.
Considering that SOTA (UMT, HTCN) is currently a style transfer driven approach, we also use CycleGAN to generate interpolated data for training to ensure relative fairness.
We are in the process of cleaning our data, you can provide your email address and I will send it to you as soon as it is done.

**Comment by Changes92** [comment]
> Sorry for the late reply to you. Considering that SOTA (UMT, HTCN) is currently a style transfer driven approach, we also use CycleGAN to generate interpolated data for training to ensure relative fairness. We are in the process of cleaning our data, you can provide your email address and I will send it to you as soon as it is done.

Thank you so much for your reply and contributions. That's ok and I can just wait for it.
